### ISSUE TITLE
Sealed class support

### ISSUE THREAD

**Issue by NebelNidas** [RaphiMC/JavaDowngrader#10]
An option to automatically apply the [`ApiStatus.NonExtendable`](https://javadoc.io/doc/org.jetbrains/annotations/latest/org/jetbrains/annotations/ApiStatus.NonExtendable.html) JetBrains Annotation to downgraded sealed classes would be nice :)

**Comment by RaphiMC** [comment]
Whats your usecase? Are you trying to use a Java 17 jar in your Java 8 project as a library? It would be better for the IDE and for your overall code if you move the whole project to 17 instead and downgrade the final built jar instead (for example with the JavaDowngrader gradle plugin). That way you can use 17 features and have things like sealed classes work as intended

**Comment by NebelNidas** [comment]
I don't have a specific use case yet, and you're right that consumers should probably just upgrade to Java 17+ instead, but adding the annotation shouldn't hurt either? I'm sure there are some edge cases where upgrading the build chain from Java 8 isn't possible yet for some obscure reason

**Comment by RaphiMC** [comment]
I already talked with @Gaming32 about this and we both came to the conclusion that we don't really want to support that use case since its very obscure and has better alternatives. If you can't update the build chain from Java 8 that should be the first thing you should work on since Java 8 is getting less and less support from libraries
